In [39]:
#import necessary libraries 
from sklearn.linear_model import LogisticRegression 
from sklearn.svm import SVC 
from sklearn.ensemble import RandomForestClassifier 
import numpy as np
from sklearn.datasets import load_digits

digits=load_digits()

In [40]:
#test and train your datset 
from sklearn.model_selection import train_test_split 
X_train,X_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [41]:
#lets first check logistic regression 
lr=LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)  #accuray is 0.968....  not bad 

C:\Users\kriti\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9722222222222222

In [42]:
#lets check for Support vector machine 
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test) 

0.9907407407407407

In [43]:
#lets check for random forest 
rf=RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test) 

0.9796296296296296

In [44]:
#lets work on K fold 
from sklearn.model_selection import KFold 
kf=KFold(n_splits=3)    #number or folds be 3
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [45]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [46]:
  # [3 4 5 6 7 8]-->training set   [0 1 2]-->testing set 
  # [0 1 2 6 7 8]-->training set   [3 4 5]-->testing set 
  # [0 1 2 3 4 5]-->training set   [6 7 8]-->testing set

In [47]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [48]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [49]:

scores_l=[]
scores_svm=[]
scores_rf=[]

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                        digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

print("Logistic Regression Scores:", scores_l)
print("SVM Scores:", scores_svm)
print("Random Forest Scores:", scores_rf)

C:\Users\kriti\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\kriti\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Logistic Regression Scores: [0.9232053422370617, 0.9415692821368948, 0.9148580968280468]
SVM Scores: [0.9666110183639399, 0.9816360601001669, 0.9549248747913188]
Random Forest Scores: [0.9348914858096828, 0.9549248747913188, 0.9282136894824707]


In [50]:
from sklearn.model_selection import cross_val_score 

In [51]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\Users\kriti\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\kriti\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [52]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [53]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.93333333, 0.92222222, 0.94986072, 0.9637883 , 0.91922006])